### ISSUE TITLE
Create new abbreviation?

### ISSUE THREAD

**Issue by reinvantveer** [GerwinBosch/LinkDaLe#42]
Other than RDF-PAQT:
Lin(k)DaLe
(or something other fancy)

**Comment by GerwinBosch** [comment]
Settings have been changed to use linkdale.org. However changing it can take up to a day

**Comment by GerwinBosch** [comment]
And for the logo might this be an idea
![naamloos](https://user-images.githubusercontent.com/7578412/30593343-80635514-9d4a-11e7-871a-6ed21b68bcac.png)

**Comment by StanRonzhin** [comment]
We can reuse getting started picture from tutorials as logo. With LinkDale you will learn hot to think in graphs.
